# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageSlideshowApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ImageSlideshow', '~> 1.9.0'
  pod "ImageSlideshow/Kingfisher"
  # Pods for ImageSlideshowApp

end
