# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExpandableTableView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ExpyTableView'
  # Pods for ExpandableTableView

end
